opitzconsulting/ansible-oracle

roles/orasw-meta/defaults/main.yml
The filename for OPatch was missing in oracle_opatch_patch.
=> orasw-meta: added OPatch for 19c

roles/common/tasks/main.yml
Oracle changed the configuration of public-yum.repo in January 2019 for OL7.
Downloading the old file will mess up the repository configuration.
=> common: Skip downloading public-yum.repo on newer OL7 versions

roles/oraswdb-install/tasks/19.3.0.0.yml, roles/oraswdb-install/tasks/main.yml
The name for the installation archive in 19c could be defined in oracle_db_homes.
Example:
db_homes_config:
db198:
home: db198
version: 19.3.0.0
imagename: db_home_19.8.zip
The imagename defines the used filename for the archive to unzip.
Please create the archive with oui before:
$ORACLE_HOME/runInstaller -createGoldImage -silent -destinationLocation "${ORACLE_BASE}/db_golden_image
=> oraswdb-install: Install 19c from Golden Image

roles/cxoracle/tasks/main.yml
A new parameter has been added to support custom source definition for cx_Oracle.
This is needed when ansible-oracle is used in environments without public internet connectivity.
How to user?
Download cx_Oracle without installation:
pip install --download /tmp 'cx_oracle<8.0'
Store the file in a directory availible from target host.
Set follwoing variable in inventory:
cx_oracle_source="file:///tmp/cx_Oracle-7.3.0-cp27-cp27mu-manylinux1_x86_64.whl"
=> cxoracle: Support custom installation source

roles/oradb-manage-db/tasks/tnsnames.yml
Currently having conditional state in tnsnames_installed is ignored and all entries found there are created. It does not even respect state: absent for removing tnsnames.ora entries.
With this change this gets fixed and tnsnames entry will only then exist, when state is defined to present in tnsnames_installed.
=> fixed a problem with thsnames ignoring state in tnsnames_installed

roles/orahost/tasks/main.yml
Some Kernels do not allow an increase of hugepages without
enough free memory. When hugepages could not be allocated
during initial setup the execution of DBCA could fail due
to missing enough hugpages.
When vm.nr_hugepages is changed the filecache is flushed
and anoher execution of systcl -p is done - hopefully to
allocate the needed pages.
=> orahost: new approach for setting hugepages during setup

roles/orahost/tasks/main.yml
The following variables have been added:
- os_timezone: <not defined by default>
- os_hwclock: <ignored by default>
Example:
os_timezone: Europe/Berlin
=> orahost: Added support for timezone change

roles/common/tasks/main.yml, roles/orahost/tasks/main.yml, roles/oraswdb-install/tasks/install-home-db.yml
It is time to move to a much newer version of Ansible, due to desupport of really old used versions of Ansible for developing this project.
The new minimum version is 2.8 and this PR is tested against 2.8 and 2.9.
=> changed minimum Ansible version to 2.8

roles/orasw-meta/defaults/main.yml, roles/oraswdb-golden-image/meta/main.yml, roles/oraswdb-golden-image/tasks/main.yml, roles/oraswgi-golden-image/meta/main.yml, roles/oraswgi-golden-image/tasks/main.yml
The role uses `gridSetup.sh -silent -createGoldImage -destinationLocation`
to create Golden Images from running installations.
The following variable must be set:
`golden_image_dest: /u01/golden`
The directroy is created by oracle.
=> Create Golden-Images for Oracle Restart and Database-Homes

roles/orahost/tasks/main.yml
lvsize in host_fs_layout did not change the lvol with underlying
Filesystem.
This has been change by adding resizefs=yes to the lvol task.
=> orahost: added resizefs=yes

roles/orahost/tasks/main.yml
We cannot use factor_os so early in orahost, due to missing facter.rpm.
=> orahost: Bugfix for factor_os is undefined

library/oracle_opatch, roles/oraswdb-manage-patches/tasks/db-home-patch.yml, roles/oraswdb-manage-patches/tasks/transfer-files.yml, roles/oraswdb-manage-patches/tasks/unpack-files.yml
Some interim patches are PSU/RU dependent. The patch ID is the same
but content, dependencies, and UPI (unique patch ID) differ. These
patches have to be rolled back in advance of applying the PSU/RU and
must afterwards be installed with the correct version (=UPI). If
{{oracle_sw_patches}} contains the files from different UPIs of the
same patch the right one has to be transferred and unpacked.
Usage is like this:
```
db_homes_config:
12.1.0.2-ee:
opatch_minversion: 12.2.0.1.17
opatch:
- { patchid: 21238475, state: absent, stop_processes: True }
- { patchid: 18633374, state: absent, excludeUPI: 22990084, stop_processes: True }
- { patchid: 29494060, state: present, stop_processes: True } # PSU
- { patchid: 18881811, state: present, stop_processes: True }
- { patchid: 18633374, state: …
```
=> oraswdb-manage-patches: Extension for UPI (Unique Patch ID)

roles/oraswgi-install/tasks/12.2.0.1.yml, roles/oraswgi-install/tasks/18.3.0.0.yml, roles/oraswgi-install/tasks/19.3.0.0.yml, roles/oraswgi-install/tasks/21.3.0.0.yml, roles/oraswgi-install/tasks/main.yml, roles/oraswgi-install/templates/grid-install.rsp.12.2.0.1.j2, roles/oraswgi-install/templates/grid-install.rsp.18.3.0.0.j2, roles/oraswgi-install/templates/grid-install.rsp.19.3.0.0.j2, roles/oraswgi-install/templates/grid-install.rsp.21.3.0.0.j2
Disable configuriation of GI Management Repository
in 19c and 21c.
This could be reenabled with follwoing variable:
oracle_gi_mgmt_repo: true
Refactoring for oracle.install.crs.config.clusterNodes.
=> oraswgi-install: Fixes for RAC-Setups

library/oracle_sql
This PR fixes #68 by ignoring quoting delimeters with single or double quotes when splitting statements in a file for oracle_sql
=> fix for quoted sqldelim fixes #68

.ansible-lint, .github/workflows/ansible-lint.yml, roles/oradb-failover/defaults/main.yml, roles/oradb-failover/tasks/main.yml, roles/oraemagent-install/defaults/main.yml, roles/oraemagent-install/tasks/main.yml, roles/orahost/tasks/main.yml, roles/oraswgi-clone/tasks/main.yml, roles/oraswgi-clone/vars/main.yml, roles/oraswgi-install/tasks/12.1.0.2.yml, roles/oraswgi-install/tasks/12.2.0.1.yml, roles/oraswgi-install/tasks/18.3.0.0.yml, roles/oraswgi-install/tasks/19.3.0.0.yml, roles/oraswracdb-clone/tasks/main.yml
The following options have been removed from skip_list
- deprecated-local-action
- deprecated-command-syntax
- ignore-errors
Fixed following roles:
- roles/oradb-failover
- roles/oraemagent-install
- roles/oraswgi-clone
- roles/oraswracdb-clone
=> ansible-lint: more ansible-lint and remove options from skip_list

roles/orahost-storage/defaults/main.yml
See: ORA-27038,ORA-01580: Error Creating Control Backup File on NFS mount point from SQL or Rman (Doc ID 2710341.1)
=> orahost-storage: added option nolock to dnfsoptions

roles/oraasm-manage-diskgroups/defaults/main.yml, roles/orahost/defaults/main.yml, roles/oraswgi-install/defaults/main.yml, roles/oraswgi-install/tasks/19.3.0.0.yml, roles/oraswgi-install/tasks/21.3.0.0.yml, roles/oraswgi-install/tasks/main.yml, roles/oraswgi-install/tasks/runcluvfy.yml, roles/oraswgi-install/templates/grid-install.rsp.19.3.0.0.j2, roles/oraswgi-install/templates/grid-install.rsp.21.3.0.0.j2
This PR includes a huge rework in oraswgi-install.
The following points are changed:
- Removed parameter -ignorePrereq during GridSetup.sh
Ignoring the check for system requirements is not a good idea by default. That created a lot of extra work after or during execution of root.sh with failures during execution.
The old behavior could be reenabled with: `gi_ignoreprereq: true`
- added asmoper to oracle user in orahost
This is a requirement in Grid-Infrastructure 19c.
- Parameter `oracle_asm_disk_string` could be set when asmlib is used
This is needed when Grid-Infrastrucuture is installed, because the default '`ORCL:*`' could create problems during requirements check in GridSetup.sh.
The '*' could be added at end of `oracle_asm_disk_string`. That was forbidden before this change and only …
=> Refactoring oraswgi-install

roles/oraswgi-install/tasks/19.3.0.0.yml, roles/oraswgi-install/tasks/21.3.0.0.yml, roles/oraswgi-install/tasks/runcluvfy.yml
- oraswgi: move from package to yum for cvuqdisk.rpm
OL8 requires a signature for all RPMs during installation.
We need to switch from package to yum with disable_gpg_check.
- oraswgi: assert OL8 and GI 19.3 without RU
ansible-oracle has no support for prepatch before execution of GrindSetup.sh.
The runclufy is stuck on OL8 when RU 19.11 is not installed.
The assert stops the execution, when no Golden-Image with RU 19.11 or
newer has been selected.
=> OL/RHEL8 fixes for Grid-Infrastructure/Restart

roles/oradb-manage-db/tasks/manage-db.yml
Creating a Cloud-Control Database from DBCA-Template is possible
without placing the template in ansible inventory.
Use the following variable inside oracle_databases to disable the
template copy from inventory.
`dbca_copy_template: false`
=> oradb-manage-db: use custom DBCA-Templates from ORACLE_HOME directly

roles/orahost/tasks/main.yml
The `host_fs_layout` could be used to changed filesystems from OS itself.
Important:
Always set the owner, group and mode for filesystems, because the
defaults are oracle:oinstall and 0775.
Example:
```
host_fs_layout:
- vgname: rootvg
state: present
filesystem:
- {mntp: /tmp, lvname: tmplv, lvsize: 1200m, fstype: ext4, owner: root, group: root, mode: 1777}
disk:
- {device: /dev/sda, pvname: /dev/sda2}
```
=> orahost: added options to host_fs_layout

roles/oradb-create/templates/dotprofile-db.j2, roles/oradb-manage-db/defaults/main.yml, roles/oradb-manage-db/tasks/manage-db.yml, roles/oradb-manage-db/templates/dotprofile-db.j2, roles/orahost/tasks/main.yml, roles/oraswdb-install/tasks/install-home-db.yml, roles/oraswdb-install/templates/dotprofile-home.j2
This PR fixes a problem where oracle user home directory has been hardcoded to be under /home.
In some installations, this is not the case and now it is possible to use oracle_user_home variable to overwrite the home path.
Also, when creating oracle user in system it is not possible to add home attribute to specify a home (this is optional)
Old and not used anymore roles have not been corrected, the oracle_user_home variable is defined in orasw-meta defaults.
It should be considered to create top level defaults, as some roles depend on orahost_meta, and some on orasw-meta... This should be clarified. For now this fixes however most of the problems where oracle home is not under /home
=> bugfix hardcoded /home/oracle - use oracle_user_home

roles/oraswdb-install/tasks/install-home-db.yml
This PR fixes problems, when after copying the golden image from ansible controller to the target host, it was looked up under wrong path.
=> bugfix: gold image copy path

library/oracle_user, roles/oradb-manage-users/tasks/main.yml
This PR fixes #79 by:
- added support to interpret password as hash instead of plaintext in dbpasswords by setting users[*].password_is_hash=true
- implemented check for password change for hashes
- implemented check for plaintext password against S: pw hash
- fixes a bug where double quotes were used in IDENTIFIED BY VALUES (oracle requires single quotes here)
- revert to module defaults for update_password parameter
=> update password really only when needed with update_password=always + support for password_hash

changelogs/fragments/107-optional_uid_gid_passwd.yaml, roles/orahost/tasks/main.yml
With this PR the uid and gid attributes in oracle_users / oracle_groups are optional. This will allow adding sudo or ssh keys to systems already having users/groups provisioned without the need of entering real system uid/gid values back into inventory.
In addition the password attribute in oracle_users is also made optional, as not to forcefully alter passwords of already present users.
Hint: For skipping the entire user/group/sudo/ssh_keys parts completely either use skip_tags, or just set oracle_users and oracle_groups to empty lists ([])
=> fix: optional uid gid password

changelogs/fragments/108-host_fs_layout.yaml, roles/orahost/tasks/main.yml
This PR allows to just set configure_host_disks false and still be able to chown/chmod mountpoints specified by filesystem attributes in host_fs_layout without the need of adding empty array "disks" attribute there, to satisfy with_subelements task (that would be ignored anyway by configure_host_disks in when condition).
=> bugfix: host_fs_layout needed disk even if configure_host_disks==false

roles/oradb_manage_grants/tasks/main.yml, roles/oradb_manage_users/tasks/main.yml
Pass ``container`` parameter to ``oracle_grants`` module and ``container_data`` to ``oracle_user`` module.
Modules already support it.
=> pass container and container_data parameters to modules
